#!/usr/bin/env bash
set -euo pipefail

test "${1:-}" = 'api'
shift
method='GET'
endpoint=''

while [ "$#" -gt 0 ]; do
  case "$1" in
    --method) method="$2"; shift 2 ;;
    --raw-field|--jq) shift 2 ;;
    --paginate) shift ;;
    repos/*) endpoint="$1"; shift ;;
    *) shift ;;
  esac
done

touch "$FAKE_GH_STATE" "$FAKE_GH_LOG"
case "$method" in
  GET)
    cat "$FAKE_GH_STATE"
    ;;
  POST)
    next=1
    if [ -s "$FAKE_GH_STATE" ]; then
      next=$(( $(tail -n 1 "$FAKE_GH_STATE") + 1 ))
    fi
    printf '%s\n' "$next" >> "$FAKE_GH_STATE"
    printf 'POST\n' >> "$FAKE_GH_LOG"
    printf '%s\n' "$next"
    ;;
  PATCH)
    id="${endpoint##*/}"
    printf 'PATCH %s\n' "$id" >> "$FAKE_GH_LOG"
    ;;
  DELETE)
    id="${endpoint##*/}"
    temporary="${FAKE_GH_STATE}.new"
    awk -v id="$id" '$0 != id' "$FAKE_GH_STATE" > "$temporary"
    mv "$temporary" "$FAKE_GH_STATE"
    printf 'DELETE %s\n' "$id" >> "$FAKE_GH_LOG"
    ;;
  *) exit 2 ;;
esac
